# -*- coding: utf-8 -*-
from setuptools import setup

packages = ["protocol_implements_decorator"]

package_data = {"": ["*"]}

with open("README.md") as f:
    readme = f.read()

setup_kwargs = {
    "name": "protocol-implements-decorator",
    "version": "1.0.0",
    "description": (
        "Adds '@implements' decorator to aid in explicit use of protocols."
    ),
    "long_description": readme,
    "long_description_content_type":'text/markdown',
    "author": "rbroderi",
    "author_email": "richard@sanguinesoftware.com",
    "maintainer": None,
    "maintainer_email": None,
    "url": "https://github.com/rbroderi/protocol_implements_decorator",
    "packages": packages,
    "package_data": package_data,
    "python_requires": ">=3.8,<4.0",
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
